version: 2

build:
  os: python:3.14-slim
  tools:
    python: "3.14"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements: [ "docs" ]
