# Copyright (c) 2026 The pymovements Project Authors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
"""Validate drift correction algorithms against the reference implementation of Carr et al.

The golden line assignments below were generated by running the reference implementation
accompanying Carr et al. 2022 (see ``CARR_REFERENCE`` for the pinned source) on the fixation
fixtures stored in ``tests/files/drift_correction/``. The tests assert that the pymovements
port reproduces the reference output exactly.

Fixture generation: each fixture is a synthetic multi-line reading trial. For each line, one
fixation per word (following the given reading path, which may contain regressions and skips)
is placed at ``x = word_x + N(0, x_sd)`` and ``y = line_y + drift_slope * x +
drift_offset * line_index + N(0, y_sd)``, using ``numpy.random.default_rng(seed)`` and
rounding to 2 decimals. The committed CSV values are canonical; the goldens were computed
from the rounded values. Fixture parameters (seed, line_ys, word_xs, paths, drift_slope,
drift_offset, x_sd, y_sd):

- baseline: 20260812, 100:340:60, 80:800:80, [0,1,2,3,4,5,3,6,7,8,9] per line, 0.02, 2.5, 6, 4
- severe_drift: 20260813, 100:340:60, 80:800:80, [0,1,2,3,1,4,5,6,7,5,8,9] per line,
  0.03, 4.0, 6, 5
- two_lines: 20260814, 150:210:60, 80:710:90, [0,1,2,3,4,2,5,6,7] per line, 0.02, 3.0, 6, 4
- irregular: 20260815, 120:300:60, 80:800:80, per-line paths [0,2,3,5,6,8,9],
  [0,1,3,4,2,6,7,9], [0,4,8], [0,1,2,4,5,3,6,7,8,9], 0.022, 3.0, 6, 4

Regeneration: download the reference via ``CARR_REFERENCE.download(target_dirpath)`` (verifies
the MD5 checksum), run each algorithm on the fixture CSV values with the word grid
``[[x, line_y] for line_y in line_ys for x in word_xs]``, and encode the corrected
y-coordinates as line indices. Stability was verified at generation time with repeated runs
(the reference uses KMeans without a fixed random state) and with input perturbations of
0.01 px. A failure of these tests after a numpy, scipy or scikit-learn upgrade therefore
requires diagnosis before regenerating any golden values: a flipped line assignment may
indicate a genuine behavioral difference rather than numerical noise.
"""
from __future__ import annotations

import numpy as np
import polars as pl
import pytest

import pymovements.events.correction.drift_algorithms as da
from pymovements import WebSource

CARR_REFERENCE = WebSource(
    url=(
        'https://raw.githubusercontent.com/jwcarr/drift/'
        '5b4b6c475b5118950514dc01960391ef0d95bd19/algorithms/Python/drift_algorithms.py'
    ),
    filename='drift_algorithms_reference.py',
    md5='c70c367328c27fcd3f02c314ee7927f4',
)

FIXTURE_LINE_YS = {
    'baseline': np.arange(100.0, 341.0, 60.0),
    'severe_drift': np.arange(100.0, 341.0, 60.0),
    'two_lines': np.arange(150.0, 211.0, 60.0),
    'irregular': np.arange(120.0, 301.0, 60.0),
}

FIXTURE_WORD_XS = {
    'baseline': np.arange(80.0, 801.0, 80.0),
    'severe_drift': np.arange(80.0, 801.0, 80.0),
    'two_lines': np.arange(80.0, 711.0, 90.0),
    'irregular': np.arange(80.0, 801.0, 80.0),
}

# Golden corrected y-coordinates, encoded as one line index per fixation.
# The 'compare' golden for 'two_lines' was generated with an explicit n_nearest_lines=2
# because the reference implementation raises an IndexError with the default of 3 on
# texts with fewer than 3 lines. The test below runs the pymovements port with the
# DEFAULT n_nearest_lines on purpose: it asserts that the clamped default reproduces the
# reference with a valid explicit parameter.
GOLDEN_LINE_ASSIGNMENTS = {
    'attach': {
        'baseline': '0000000000011111111111222222222223333333333344444444444',
        'severe_drift': '000000000010111111111112222222222223333333344344444444444444',
        'two_lines': '000000000111111111',
        'irregular': '0000000111111112223333333333',
    },
    'chain': {
        'baseline': '0000000000011111111111222222222223333333333344444444444',
        'severe_drift': '000000000000111111111111222222222233333333333344444444444444',
        'two_lines': '000000000111111111',
        'irregular': '0000000111111112223333333333',
    },
    'cluster': {
        'baseline': '0000000000011111111111222222222223333333333344444444444',
        'severe_drift': '000000000000111111111111222222222222333333333333444444444444',
        'two_lines': '000000000111111111',
        'irregular': '0000000111111112223333333333',
    },
    'compare': {
        'baseline': '0000000000011111111111222222222223333333333344444444444',
        'severe_drift': '000000000000111111111111222222222222333333333333444444444444',
        'two_lines': '000000000111111111',
        'irregular': '0000000111111112223333333333',
    },
    'merge': {
        'baseline': '0000000000011111111111222222222223333333333344444444444',
        'severe_drift': '000000000000111111111111222222222222333333333333444444444444',
        'two_lines': '000000000111111111',
        'irregular': '0000000111111112223333333333',
    },
    'regress': {
        'baseline': '0000000000011111111111222222222223333333333344444444444',
        'severe_drift': '000000000000111111111111222222222222333333333333444444444444',
        'two_lines': '000000000111111111',
        'irregular': '0000000111111112223333333333',
    },
    'segment': {
        'baseline': '0000000000011111111111222222222223333333333344444444444',
        'severe_drift': '000000000000111111111111222222222222333333333333444444444444',
        'two_lines': '000000000111111111',
        'irregular': '0000000111111112223333333333',
    },
    'slice': {
        'baseline': '0000000000011111111111222222222223333333333344444444444',
        'severe_drift': '000000000000111111111111222222222222333333333333444444444444',
        'two_lines': '000000000111111111',
        'irregular': '0000000111111112223333333333',
    },
    'split': {
        'baseline': '0000000000011111111111222222222223333333333344444444444',
        'severe_drift': '000000000000111111111111222222222222333333333333444444444444',
        'two_lines': '000000000111111111',
        'irregular': '0000000111111112223333333333',
    },
    'stretch': {
        'baseline': '0000000000011111111111222222222223333333333344444444444',
        'severe_drift': '000000000000000000000000111111111111222222222222333333333333',
        'two_lines': '000000000111111111',
        'irregular': '0000000111111112223333333333',
    },
    'warp': {
        'baseline': '0000000000011111111111222222222223333333333344444444444',
        'severe_drift': '000000000000111111111111222222222222333333333333444444444444',
        'two_lines': '000000000111111111',
        'irregular': '0000000111111112223333333333',
    },
}

# Dynamic time warping golden: first line of the baseline fixture (11 fixations)
# against the first line of its word grid (10 words).
DTW_COST = 260.15870640329126
DTW_PATH = [[0], [1], [2], [3], [4], [5], [5], [6], [7], [8], [9]]


def load_fixture(testfiles_dirpath, fixture_name):
    """Load a fixation fixture CSV as an array of shape (N, 2)."""
    csv_path = testfiles_dirpath / 'drift_correction' / f'{fixture_name}.csv'
    return pl.read_csv(csv_path).select(['fixation_x', 'fixation_y']).to_numpy()


def word_xy_grid(fixture_name):
    """Build the word center grid of a fixture, y being the line position (Carr et al.)."""
    return np.array([
        [word_x, line_y]
        for line_y in FIXTURE_LINE_YS[fixture_name]
        for word_x in FIXTURE_WORD_XS[fixture_name]
    ])


@pytest.mark.parametrize('fixture_name', list(FIXTURE_LINE_YS))
@pytest.mark.parametrize('algorithm', list(GOLDEN_LINE_ASSIGNMENTS))
def test_algorithm_matches_reference_implementation(
        algorithm, fixture_name, testfiles_dirpath,
):
    fixation_xy = load_fixture(testfiles_dirpath, fixture_name)
    line_ys = FIXTURE_LINE_YS[fixture_name]

    if algorithm in {'compare', 'warp'}:
        target = word_xy_grid(fixture_name)
    else:
        target = line_ys

    result = getattr(da, algorithm)(fixation_xy, target)

    # x-coordinates must pass through unchanged and every output y must be a line position.
    np.testing.assert_array_equal(result[:, 0], fixation_xy[:, 0])
    assert set(result[:, 1]) <= set(line_ys)

    golden_digits = GOLDEN_LINE_ASSIGNMENTS[algorithm][fixture_name]
    expected_y = line_ys[np.array([int(digit) for digit in golden_digits])]
    np.testing.assert_array_equal(result[:, 1], expected_y)


def test_dynamic_time_warping_matches_reference_implementation(testfiles_dirpath):
    fixation_xy = load_fixture(testfiles_dirpath, 'baseline')
    word_xy = word_xy_grid('baseline')

    cost, path = da.dynamic_time_warping(fixation_xy[:11], word_xy[:10])

    assert cost == pytest.approx(DTW_COST)
    assert path == DTW_PATH
