name: dataset-docs

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    name: regenerate dataset docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pymovements repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pymovements
        run: python -m pip install -e .

      - name: Write dataset docpage RST files
        run: python src/pymovements/_scripts/write_dataset_docpages.py

      - name: Commit changes
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
